version: '3'
services:
  db:
    image: mysql:5.5.62
    environment:
      MYSQL_ROOT_PASSWORD: takumi-21
    ports:
      - "3306:3306"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/app_name
    ports:
      - "8080:8080"
    depends_on:
      - db